SUPL_HOST=supl.google.com
SUPL_PORT=7275
SUPL_VER=0x20000
SUPL_MODE=1

NTP_SERVER=time.google.com

XTRA_SERVER_1=https://path1.xtracloud.net/xtra3grcej.bin
XTRA_SERVER_2=https://path2.xtracloud.net/xtra3grcej.bin
XTRA_SERVER_3=https://path3.xtracloud.net/xtra3grcej.bin
