# Google's — real GApps via MindTheGapps. No microG, no F-Droid.
#
# MindTheGapps ships as a flashable zip (copy-native), so it is extracted into
# vendor/gapps/ and wired with PRODUCT_COPY_FILES by vendor/gapps/gapps.mk
# (generated by vendor/lieppos/tools/extract-mindthegapps.sh). inherit-if-exists
# so the flavor still configures cleanly before the extraction is run.

PRODUCT_PACKAGES += \
    TinyScreenService

$(call inherit-product-if-exists, vendor/gapps/gapps.mk)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.lieppos.flavor=gapps
