#!/usr/bin/env bash
# Extract a MindTheGapps flashable zip into vendor/gapps/ as build-inheritable
# prebuilts, and (re)generate vendor/gapps/gapps.mk plus vendor/gapps/Android.mk.
# MindTheGapps is copy-native (it just drops files into product/ and system_ext/),
# so we mirror that layout into the build. Android 16 rejects APKs in
# PRODUCT_COPY_FILES, so APKs are emitted as BUILD_PREBUILT modules instead.
#
# Usage:
#   vendor/lieppos/tools/extract-mindthegapps.sh [path/to/MindTheGapps-*.zip]
#
# Default zip: newest MindTheGapps-*-arm64-*.zip in ~/Downloads.
set -euo pipefail

TOP="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
DEST="$TOP/vendor/gapps"
PROP="$DEST/proprietary"

ZIP="${1:-}"
if [ -z "$ZIP" ]; then
    ZIP="$(ls -1t "$HOME"/Downloads/MindTheGapps-*-arm64-*.zip 2>/dev/null | head -1 || true)"
fi
[ -n "$ZIP" ] && [ -f "$ZIP" ] || { echo "MindTheGapps zip not found: '$ZIP'"; exit 1; }
echo "Source: $ZIP"

rm -rf "$PROP"
mkdir -p "$PROP"
# Pull only the partition payload (system/product, system/system_ext, ...).
unzip -o -q "$ZIP" 'system/*' -d "$DEST/.unzip"
# Strip the leading system/ so paths are product/... and system_ext/...
shopt -s nullglob
mv "$DEST/.unzip/system/"* "$PROP/"
rm -rf "$DEST/.unzip"

MK="$DEST/gapps.mk"
ANDROID_MK="$DEST/Android.mk"
APK_MODULES=()
COPY_FILES=()

module_name_for() {
    local rel="$1"
    printf 'GApps_%s' "$(basename "$rel" .apk)" | tr -c 'A-Za-z0-9_.+-' '_'
}

emit_apk_module() {
    local sub="$1" rel="$2"
    local src="proprietary/$sub/$rel"
    local module stem dir class partition privileged relative module_path

    module="$(module_name_for "$rel")"
    stem="$(basename "$rel")"
    dir="$(dirname "$rel")"
    class="APPS"
    partition=""
    privileged=""
    relative=""
    module_path=""

    case "$sub" in
        product) partition="LOCAL_PRODUCT_MODULE := true" ;;
        system_ext) partition="LOCAL_SYSTEM_EXT_MODULE := true" ;;
        system) partition="" ;;
        *) echo "Unsupported partition for APK: $sub/$rel" >&2; exit 1 ;;
    esac

    case "$dir" in
        app/*) relative="${dir#app/}" ;;
        priv-app/*) privileged="LOCAL_PRIVILEGED_MODULE := true"; relative="${dir#priv-app/}" ;;
        overlay)
            if [ "$sub" = product ]; then
                module_path='LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay'
            elif [ "$sub" = system_ext ]; then
                module_path='LOCAL_MODULE_PATH := $(TARGET_OUT_SYSTEM_EXT)/overlay'
            else
                module_path='LOCAL_MODULE_PATH := $(TARGET_OUT)/overlay'
            fi
            ;;
        *)
            # Fallback for unusual APK locations: install to the original directory.
            if [ "$sub" = product ]; then
                module_path="LOCAL_MODULE_PATH := \$(TARGET_OUT_PRODUCT)/$dir"
            elif [ "$sub" = system_ext ]; then
                module_path="LOCAL_MODULE_PATH := \$(TARGET_OUT_SYSTEM_EXT)/$dir"
            else
                module_path="LOCAL_MODULE_PATH := \$(TARGET_OUT)/$dir"
            fi
            ;;
    esac

    APK_MODULES+=("$module")

    {
        echo
        echo "include \$(CLEAR_VARS)"
        echo "LOCAL_MODULE := $module"
        echo "LOCAL_MODULE_TAGS := optional"
        echo "LOCAL_SRC_FILES := $src"
        echo "LOCAL_MODULE_CLASS := $class"
        echo "LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)"
        [ "$stem" = "$module.apk" ] || echo "LOCAL_INSTALLED_MODULE_STEM := $stem"
        [ -n "$partition" ] && echo "$partition"
        [ -n "$privileged" ] && echo "$privileged"
        [ -n "$relative" ] && echo "LOCAL_MODULE_RELATIVE_PATH := $relative"
        [ -n "$module_path" ] && echo "$module_path"
        echo "LOCAL_CERTIFICATE := PRESIGNED"
        echo "LOCAL_ENFORCE_USES_LIBRARIES := false"
        echo "LOCAL_DEX_PREOPT := false"
        echo "include \$(BUILD_PREBUILT)"
    } >> "$ANDROID_MK"
}

scan_part() {
    local sub="$1" outvar="$2"
    [ -d "$PROP/$sub" ] || return 0
    while IFS= read -r -d '' f; do
        local rel="${f#"$PROP/$sub/"}"
        if [[ "$rel" == *.apk ]]; then
            emit_apk_module "$sub" "$rel"
        else
            COPY_FILES+=("vendor/gapps/proprietary/$sub/$rel:\$($outvar)/$rel")
        fi
    done < <(find "$PROP/$sub" -type f -print0 | sort -z)
}

{
    echo "# AUTO-GENERATED by vendor/lieppos/tools/extract-mindthegapps.sh — do not edit."
    echo "# Source zip: $(basename "$ZIP")"
    echo "# Real Google GApps (MindTheGapps). Inherited by vendor/lieppos/flavors/gapps.mk."
    echo
    echo "LOCAL_PATH := \$(call my-dir)"
} > "$ANDROID_MK"

scan_part product     TARGET_COPY_OUT_PRODUCT
scan_part system_ext  TARGET_COPY_OUT_SYSTEM_EXT
scan_part system      TARGET_COPY_OUT_SYSTEM

{
    echo "# AUTO-GENERATED by vendor/lieppos/tools/extract-mindthegapps.sh — do not edit."
    echo "# Source zip: $(basename "$ZIP")"
    echo "# Real Google GApps (MindTheGapps). Inherited by vendor/lieppos/flavors/gapps.mk."
    echo

    if [ "${#APK_MODULES[@]}" -gt 0 ]; then
        echo "PRODUCT_PACKAGES += \\"
        for i in "${!APK_MODULES[@]}"; do
            if [ "$i" -eq $((${#APK_MODULES[@]} - 1)) ]; then
                printf '    %s\n' "${APK_MODULES[$i]}"
            else
                printf '    %s \\\n' "${APK_MODULES[$i]}"
            fi
        done
        echo
    fi

    if [ "${#COPY_FILES[@]}" -gt 0 ]; then
        echo "PRODUCT_COPY_FILES += \\"
        for i in "${!COPY_FILES[@]}"; do
            if [ "$i" -eq $((${#COPY_FILES[@]} - 1)) ]; then
                printf '    %s\n' "${COPY_FILES[$i]}"
            else
                printf '    %s \\\n' "${COPY_FILES[$i]}"
            fi
        done
    fi
} > "$MK"

echo "Wrote $MK (${#COPY_FILES[@]} copied files, ${#APK_MODULES[@]} APK modules)"
echo "Wrote $ANDROID_MK (${#APK_MODULES[@]} APK modules)"
echo "APKs: $(find "$PROP" -name '*.apk' | wc -l)"
