#!/usr/bin/env bash
# Extract a MindTheGapps flashable zip into vendor/gapps/ as build-inheritable
# prebuilts, and (re)generate vendor/gapps/gapps.mk with the PRODUCT_COPY_FILES
# mapping. MindTheGapps is copy-native (it just drops files into product/ and
# system_ext/), so we mirror that layout into the build.
#
# Usage:
#   vendor/lieppos/tools/extract-mindthegapps.sh [path/to/MindTheGapps-*.zip]
#
# Default zip: newest MindTheGapps-*-arm64-*.zip in ~/Downloads.
set -euo pipefail

TOP="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
DEST="$TOP/vendor/gapps"
PROP="$DEST/proprietary"

ZIP="${1:-}"
if [ -z "$ZIP" ]; then
    ZIP="$(ls -1t "$HOME"/Downloads/MindTheGapps-*-arm64-*.zip 2>/dev/null | head -1 || true)"
fi
[ -n "$ZIP" ] && [ -f "$ZIP" ] || { echo "MindTheGapps zip not found: '$ZIP'"; exit 1; }
echo "Source: $ZIP"

rm -rf "$PROP"
mkdir -p "$PROP"
# Pull only the partition payload (system/product, system/system_ext, ...).
unzip -o -q "$ZIP" 'system/*' -d "$DEST/.unzip"
# Strip the leading system/ so paths are product/... and system_ext/...
shopt -s nullglob
mv "$DEST/.unzip/system/"* "$PROP/"
rm -rf "$DEST/.unzip"

MK="$DEST/gapps.mk"
{
    echo "# AUTO-GENERATED by vendor/lieppos/tools/extract-mindthegapps.sh — do not edit."
    echo "# Source zip: $(basename "$ZIP")"
    echo "# Real Google GApps (MindTheGapps). Inherited by vendor/lieppos/flavors/gapps.mk."
    echo
    echo "PRODUCT_COPY_FILES += \\"
} > "$MK"

emit_part() {
    local sub="$1" outvar="$2"
    [ -d "$PROP/$sub" ] || return 0
    while IFS= read -r -d '' f; do
        local rel="${f#"$PROP/$sub/"}"
        printf '    vendor/gapps/proprietary/%s/%s:$(%s)/%s \\\n' \
            "$sub" "$rel" "$outvar" "$rel" >> "$MK"
    done < <(find "$PROP/$sub" -type f -print0 | sort -z)
}

emit_part product     TARGET_COPY_OUT_PRODUCT
emit_part system_ext  TARGET_COPY_OUT_SYSTEM_EXT
emit_part system      TARGET_COPY_OUT_SYSTEM

# Trim the trailing backslash on the last line.
sed -i '$ s/ \\$//' "$MK"

echo "Wrote $MK ($(grep -c ':' "$MK") files)"
echo "APKs: $(find "$PROP" -name '*.apk' | wc -l)"
